# Stage 1: Compile and Build angular codebase

# Use official node image as the base image
FROM node:19.3.0 as build

# Set the working directory
WORKDIR /usr/local/app

COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .
# Add the source code to app

EXPOSE 3000
CMD [ "node", "server.js", "--host 0.0.0.0" ]